### ISSUE TITLE
Add a details view showing the discussion thread and tags

### ISSUE THREAD

**Issue by izharaazmi** [joomla-extensions/patchtester#161]
Add a details view showing the discussion thread and tags. This could be a minimal layout which gives details relates for the patch.

If not much then it could be even:
* An Iframe showing the github PR page.
* A modal showing the first (or more) comments formatted according to the github markdown style.

**Comment by mbabker** [comment]
That's exactly why the "GitHub" and "J! Issue" buttons are on the list view.  You're taken directly to the relevant item on those two sites.

I'm not adding code to pull the entire issue thread when fetching data.  The number of API requests to pull that off is too many and in general if it causes things to stop working with anonymous API requests I'm not doing it.

**Comment by izharaazmi** [comment]
Loved the phrase "I'm not doing it." 👍 

I understand its a waste calling apis for more details. However, the actual list which get you the list of pulls returns the initial comment and more other relevant details already. Can't we use it for quick lookup within the component? For more information user always has a choice to go relevant pages.

**Comment by mbabker** [comment]
The first couple hundred characters of the issue's description are used as a tooltip on the issue's title.  Issue is it's still in markdown format (because it would need added API calls to convert it to HTML or inclusion of a PHP markdown library to parse it into plain text), so with the standardized template it's not useful at all anymore.

I hesitate to make it something that can display inline because some of the issue bodies get excessively long, especially when folks copy/paste the output from the sys info text file into the issue instead of adding it as a file attachment.  Plus, again rendering it means doing something to convert the markdown into a human readable format.

Ya, it's a little slow to click a button and go to a third party website, but all of the issue context can be found there.  And to me that's still a better option than giving a small snippet of data in the component which may not have all the needed information to do anything with an issue.

<img width="560" alt="screen shot 2016-06-15 at 8 02 21 am" src="https://cloud.githubusercontent.com/assets/368545/16080676/9598aa88-32cf-11e6-9d5b-0527afb40a36.png">
