### ISSUE TITLE
Fatal error on installing 3.0.0-alpha

### ISSUE THREAD

**Issue by roland-d** [joomla-extensions/patchtester#164]
#### Steps to reproduce the issue
1. Download the 3.0.0-alpha zip package
2. Install it via the Joomla Extension manager

#### Expected result
A successful installation message

#### Actual result
A Fatal error:
![patchtester_fatal_error](https://cloud.githubusercontent.com/assets/359377/16441922/984567e4-3dce-11e6-91da-7390d49ce996.png)

#### System information (as much as possible)
PHP Built On 	Windows NT CABERAWIT 10.0 build 10240 (Windows 10) AMD64
Database Version 	5.7.9
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.16
Web Server 	Apache/2.4.17 (Win64) PHP/5.6.16
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by MATsxm** [comment]
See in the README that 

> Minimum supported Joomla! version is now 3.6

I guess there's a start of explaination

**Comment by mbabker** [comment]
Yep.  The install script relies on https://github.com/joomla/joomla-cms/commit/e05aa66333af9f2fd2142ea513f452218c3eb526 to have been merged.

I thought about checking for the class' existence and throwing an exception but the calls to `JInstallerAdapter::setupScriptfile()` aren't wrapped in a try/catch so that exception would bubble up the call stack and instead of a graceful abort of the extension install it would hard fail partway through.  I could stub it, but then that defeats the point of using it IMO.  And sadly, there isn't any way to tell the installer any sooner that the extension is only supported on X version of Joomla.  I've got a rock on one side and a hard place on the other.

**Comment by roland-d** [comment]
@MATsxm Thanks for that. I did check the commit history but missed the README.

@mbabker No worries, will check it another time on 3.6.

**Comment by alex7r** [comment]
Tested on Joomla! 3.6.0-alpha
Installation falls with Fatal Error.

**Comment by mbabker** [comment]
Closing.  Without backing out the changes that use the core installer script, there isn't anything "good" that can be done here.
