### ISSUE TITLE
[3.0 B2] Table doesn't exist error

### ISSUE THREAD

**Issue by ciar4n** [joomla-extensions/patchtester#186]
#### Steps to reproduce the issue
Getting a table doesn't exist error when installing 3.0 Beta2 on a fresh Joomla! installation..

`1146 Table 'joomla-cms.#__patchtester_pulls' doesn't exist`

**Comment by mbabker** [comment]
It gets reported on occasion but it's not something I've ever been able to duplicate.

FWIW I installed the package fresh on 4.0 right after tagging it and had no issue.

**Comment by brianteeman** [comment]
I can replicate it on all versions. 

It only really happens in dev environments where you are reinstalling joomla 

1. Install patchtester and make sure it is all working
2. Delete configuration.php and reinstall joomla
3. Install pathctester again from the zip
4. Now go to patchtester and you have the error
5. uninstall patchtester and reinstall and its all good

So it is something to do with installing patchtester onto a filesystem that already has the files preventing the database creation step from completing

**Comment by mbabker** [comment]
That sounds like an issue in the core component install adapter then, I'm not doing anything here to alter the install routine in a way to break that.

**Comment by brianteeman** [comment]
possibly but i havent seen it anywhere else

**Comment by mbabker** [comment]
It is a core issue, but it can possibly be worked around.  At least with the component adapter, if it detects that an extension already exists in the filesystem, it internally switches to the update path instead of install.  The update path does not trigger the new install SQL file instructions but runs through all the updates instead.  So this should parse through all of the SQL update files since it starts with a 0.0.0 dummy version if a schema record isn't found (which with that set of instructions, would be the case).  I think by putting the right schema data into the base 2.0 schema version (done in https://github.com/joomla-extensions/patchtester/commit/e9c99d9a1ce37df5008067d6259a7001bd5b8962) it should be able to create the tables in that scenario.

**Comment by kofaysi** [comment]
Experienced a similar issue, when restoring Joomla using Akeeba Kickstar. The following two errors:
![image](https://user-images.githubusercontent.com/17022173/54487201-79101400-4893-11e9-913f-420a512f31aa.png)
![image](https://user-images.githubusercontent.com/17022173/54487206-7f9e8b80-4893-11e9-9c33-7e091582ce78.png)
Dropping the two #_patchtester SQL tables and deleting the line with "patchtester" 
in #_extensions table did not help.

Uninstalling the plugin helped. (I did not expect it to be installed at all.)

**Comment by richard67** [comment]
@kofaysi Could you test if PR #221 solves the problem you mentioned in your comment above?

**Comment by roland-d** [comment]
@ciar4n Going to close this as Michael and Richard have made some changes to handle this. Feel free to reopen if the issue still happens.
