### ISSUE TITLE
[4.0] Fetch Data stop at "Page 1"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla-extensions/patchtester#187]
#### Steps to reproduce the issue
Click "Fetch Data", in Modal-Window stops at `Processing page 1 of GitHub data`. Quit Modal-Window and reload Patchtester-Tab get PRs.
#### System information (as much as possible)
Joomla! 4.0-nightly builds
macOS Sierra, 10.12.3
Safari 10.0.3
PHP 7.0.15
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by mbabker** [comment]
As the notification says, patch tester support on 4.0 is experimental at best right now.  It isn't feasible to keep it in sync with 4.0 while it's still undergoing changes (actually a proper 4.0 layout wasn't even added to the code until after the last beta was tagged, and that doesn't yet include JavaScript changes that are required).

It seems someone has busted the JavaScript in `core.js`.  Or there's some other B/C break with the new JavaScript and/or template that has to be reverse engineered since right now there is zero documentation on the changes.

```sh
Uncaught TypeError: Cannot read property 'joomla.jtext' of null
    at Object.Joomla.getOptions (core.js?1fef521…:129)
    at Object._ (core.js?1fef521…:74)
    at Object.error (fetcher.js?1fef521…:81)
    at fire (jquery.js?1fef521…:3305)
    at Object.fireWith [as rejectWith] (jquery.js?1fef521…:3435)
    at done (jquery.js?1fef521…:9244)
    at XMLHttpRequest.<anonymous> (jquery.js?1fef521…:9484)
```

**Comment by franz-wohlkoenig** [comment]
thanks @mbabker

**Comment by zero-24** [comment]
@C-Lodder @dgt41 can you help here with a JavaScript migration guide for 4.0?

**Comment by zero-24** [comment]
@franz-wohlkoenig i think we should keep this open as this is still a issue even if the 4.0 support is ecperimental :smile:

**Comment by mbabker** [comment]
The experimental warning is really just more to say "don't expect everything to work right all the time", not "it's 4.0, no bug fixes ever".

**Comment by mbabker** [comment]
Turns out this wasn't a JavaScript error, rather a minor B/C break between `JHttpResponse` in 3.x and `Joomla\Http\Response` in 4.0.  This is fixed, though I could still use help with the JavaScript migration.
