### ISSUE TITLE
First 48 PR are fetched

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla-extensions/patchtester#192]
#### Steps to reproduce the issue
Reset Patch Tester, fetch Data: New PR are fetched, today till #15619. 
### System information
3.7.1-dev
macOS Sierra, 10.12.4
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35
### Additional comments
I know this incomplete Fetching by testing J4, now it happens in J3 too.

**Comment by wojsmol** [comment]
Issue confirmed on Joomla! 3.6.5 with patch tester 3.0.0-beta on:
Windows 8.1
php 5.6
XAMP
It looks like it is getting only 1 page of data from github.

**Comment by alikon** [comment]
for 3.0.0-beta -> [Bumped minimum requirement to Joomla! 3.7](https://github.com/joomla-extensions/patchtester/releases)
not tested on staging though

**Comment by mbabker** [comment]
48 wouldn't even be the first page, the PRs are fetched in batches of 100.  That would imply some kind of bad data with one of the PR items or some other code issue.

https://github.com/joomla-extensions/patchtester/commit/1a5b47a1080757170bf8aef9a138b2e02e85c487 fixed fetching on latest 4.0 branch but there hasn't been a tagged release including that yet.

The current development HEAD package is included here.  Just in case this is something already addressed since the last beta package.  [com_patchtester.zip](https://github.com/joomla-extensions/patchtester/files/977231/com_patchtester.zip)

**Comment by franz-wohlkoenig** [comment]
@mbabker installed last beta package, smilar Result: first 51 PR are fetched.

**Comment by mbabker** [comment]
What's the last item you're getting?  If I'm counting right https://github.com/joomla/joomla-cms/pull/15639 is the last one that should load and https://github.com/joomla/joomla-cms/pull/15634 doesn't.

**Comment by franz-wohlkoenig** [comment]
Correct, get #15639 as latest.

**Comment by Quy** [comment]
Confirmed. The last one is #15653 with the first one #15819.
