### ISSUE TITLE
Revert #230

### ISSUE THREAD

**Issue by mbabker** [joomla-extensions/patchtester#235]
https://github.com/joomla-extensions/patchtester/pull/230 should be reverted.

4.0 is not stable.  The intent of the message was to warn users of this and that a core change in 4.0 can break the component and website if the change is applied (as a number of changes seem to need deleting of a file or completely reinstalling the site).  The message should only be removed when reaching the RC phase since at that point the software by most sane versioning definitions should be stable enough.

**Comment by roland-d** [comment]
Showing a message is fine but showing it like this is not workable:
![image](https://user-images.githubusercontent.com/359377/77225410-1ff65280-6b6f-11ea-82b5-ffbfeb0704f2.png)

Having to click the X on every page load because it overlaps the GUI is far from user friendly. I would rather see something like this:

![image](https://user-images.githubusercontent.com/359377/77225478-c5a9c180-6b6f-11ea-9a7b-b7d6ec404d57.png)

**Comment by mbabker** [comment]
Blame the template changing the inbuilt message queue to a popup on every page.  It was a less annoying Bootstrap alert before that.

**Comment by roland-d** [comment]
Setting this to on hold while we wait for Joomla CMS to sort out the popup.

**Comment by SharkyKZ** [comment]
Popup thing has been sorted out in the CMS.

**Comment by roland-d** [comment]
Thank you for the heads-up
