### ISSUE TITLE
Database not up to date

### ISSUE THREAD

**Issue by blueforce** [joomla-extensions/patchtester#266]
#### Steps to reproduce the issue
1. Install Patchtester RC2 on a fresh Joomla! 4.0 Beta-dev actual nightly build
2. Install from URL: https://github.com/joomla-extensions/patchtester/releases/download/4.0.0-rc2/com_patchtester.zip
3. Go to System > Information > Database

#### Expected result
Database are up to date

#### Actual result
Database has found 1 Problem (from Patchtester) open to repair
Click on repair > Repair failed
<img width="1517" alt="Bildschirmfoto 2020-04-07 um 13 27 40" src="https://user-images.githubusercontent.com/1141234/78750929-881ba580-7971-11ea-9a08-be24ed9c854e.png">

**Comment by richard67** [comment]
@blueforce First of all, this is not a patchtester issue, it is a Joomla CMS issue. Please hover over the red "One Problem" badge. A tool tip will shows then which errors there are in detail. If this fits to what is reported in this CMS issue [https://github.com/joomla/joomla-cms/issues/28530](https://github.com/joomla/joomla-cms/issues/28530) and if you are using MySQL database server version 8.0.19 (or later, if there is any later) then it is already solved in the CMS' staging branch by Pull Request (PR) [https://github.com/joomla/joomla-cms/pull/28501](https://github.com/joomla/joomla-cms/pull/28501). This will be included in the next release 3.9.17 and soon after that release is out be merged up to the 4.0-dev branch of the CMS, then it will also be solved in Joomla 4.

Please check and close this issue here if I'm right.

**Comment by richard67** [comment]
@blueforce Wait, I just see the errors are reported for the patchtester, not the CMNS. But it still could be the same error. Please confirm if 1. you have MySQL 8.0.19 or later, and 2. if all errors are related to columns of type int(x) or tinyint(y), with x ynd y being some integer numbers. If so, then it's the same error as I mentioned above.

**Comment by richard67** [comment]
@blueforce And please check the tool tip and make a screenshot and post back here. And report back database type and version, too. Thanks in advance.

**Comment by richard67** [comment]
Can't replicate, neither with nightly build of tonight nor with a current 4.0-dev, both with Patchtester 4.0.0-rc2 on Linux server with MySQL 8.0.19 ... seems to be a different problem than the one I thought ... need screenshot of tooltip to see what the error is.

**Comment by blueforce** [comment]
Ok thank you @richard67 
Confirmed, its a J! Core DB issue, the collation is utf8_general_ci without mb4
My Setup is: PHP 7.3.x and mysql  5.7.24-cll-lve
So I close this issue
--

**Comment by richard67** [comment]
@blueforce Database collation doesn't matter, it is just a default given for the case there is no character set and collation given in the create table statement. So there should not be a problem. Could you report back where you have utf8 without mb4? Relevant is the collation of the particular database tables and their columns.

**Comment by blueforce** [comment]
I had 2 tables without mb4:
- #__finder_terms_commons
- #___ysts_tokens

**Comment by richard67** [comment]
@blueforce `#__finder_terms_common` should have had utf8mb4_unicode_ci. I have to check if there is something wrong in the CMS and will make a PR, if so. `#___ysts_tokens` Sounds like 3rd party, except if the `#___ysts_tokens` is a typo and should be `#__finder_tokens`.

**Comment by blueforce** [comment]
I have a Install from launch.joomla.org (CloudAccess.net)

**Comment by richard67** [comment]
@blueforce I've just corrected by comment above. Question: This launch.joomla.org installation, was it a J4 from beginning on, or was it a J3 updated to J4?

**Comment by blueforce** [comment]
no, it was a fresh install J4 from a nightly build (date from end of march, 26.03.)
<img width="578" alt="Bildschirmfoto 2020-04-08 um 10 04 32" src="https://user-images.githubusercontent.com/1141234/78759754-670e8100-7980-11ea-9eef-6e7abb7ffca6.png">
