### ISSUE TITLE
Fetch data for used Joomla-Version

### ISSUE THREAD

**Issue by gostn** [joomla-extensions/patchtester#300]
#### Steps to reproduce the issue
Patchtester fetch all pr for all branches. 

#### Expected result
Patchtester downlad pr for used joomla-Version. Example: Using J4: 3.10-, staging-pr not download.

**Comment by roland-d** [comment]
Hello,

Thank you for your report. This is not something I will implement because Patch Tester is downloading the pull requests for the `Joomla` repository and we do not specify a specific branch. This will be problematic as we never know which branch to pull exactly. So if I set it now to 4.0, users would not be able to get the requests for 4.1.

I understand that the 3.10 branch for example is of no use but this is the same going forward. A pull request for Joomla 5 later most likely won't work on Joomla 4 either.

By getting all the branches, the user can decide which branch to use. This is not only for the Joomla repository, you can also add custom repositories, then it is not even known which branches to use.

In this case I think we should inform users in the documentation on how to use it rather than to limit the extension.

**Comment by gostn** [comment]
i was not asking for a specific branch, but for downloading branches depending of used Joomla-Version. Example: if J3 is used, downlad all J3-Branches.

**Comment by roland-d** [comment]
How would we know which branches are J3/J3/Jx branches?

**Comment by gostn** [comment]
as shown in patchtester 
![Screen Shot 2020-10-10 at 12 14 25](https://user-images.githubusercontent.com/71960554/95652547-2b50a180-0af2-11eb-9501-fbc435b8fc59.png)

**Comment by roland-d** [comment]
The Patch Tester doesn't know which branch is what, it is just text. These branches come in with the pull requests. To do what you are asking, we should put in the code `3.10-dev` and `4.0-dev` etc. There is no flexibility then. If there would be a `3.11` branch, it would never show up because it is not in the code.

**Comment by gostn** [comment]
> These branches come in with the pull requests.

ah, understand, thanks for your explain.

**Comment by roland-d** [comment]
No problem, thank you for your suggestions.
