### ISSUE TITLE
URL in post install message returned a 404

### ISSUE THREAD

**Issue by TLWebdesign** [joomla-extensions/patchtester#323]
#### Steps to reproduce the issue
Install patch tester
click on the link to fill in github details

#### Expected result

get configuration page

#### Actual result
404 error because of bad url:

https://j4.domain.nl/administrator/_QQ__QQ_index.php?option=com_config&view=component&component=com_patchtester&returnurl=aW5kZXgucGhwP29wdGlvbj1jb21fcGF0Y2h0ZXN0ZXI=#authentication_QQ__QQ_

#### System information (as much as possible)
J4 Beta 8-dev

**Comment by roland-d** [comment]
Hello @TLWebdesign Are you using the patchtester with a different language than English?

**Comment by TLWebdesign** [comment]
Hi Roland, yeah i had it set to dutch.

**Comment by roland-d** [comment]
Hello @TLWebdesign So I checked and this is an issue in the Dutch language files where they use QQ around the quotes. This is not something I can fix in the Patch Tester itself but needs to be fixed in the language file. You can contribute to the Dutch language file here: https://joomla.crowdin.com/patch-tester-extension#languages

I am closing the issue here.
