### ISSUE TITLE
Trim whitespaces from search query

### ISSUE THREAD

**Issue by Babofett** [joomla-extensions/patchtester#331]
#### Steps to reproduce the issue
In the patch tester view, insert the title of an existing PR in the search bar, but add a trailing space to the end of the query.  

https://user-images.githubusercontent.com/46003718/129696908-2b1f6389-a1ab-44b9-9d9f-802eda7441b8.mp4

#### Expected result
A list with matching PRs.

#### Actual result
No matching results.

#### System information (as much as possible)
Using Brave on KDE Neon with XAMPP, PHP7.4.3, VS Code

**Comment by roland-d** [comment]
Hello @Babofett Thank you for your request. Github does not send me an email on a new issue so hence a late reply. In my opinion there is no bug here as you entered a space in the search field, so it searches for a field. All the other lists in Joomla do not trim the search field either. In case you do want to search on a space, you cannot because we would remove it. An example is where a word can be used as standalone or as part of word. For example the word  `item` is used alone but also in `items`. In this case you would no longer be able to filter on the word `item` alone.
