### ISSUE TITLE
Table 'j4_db.xcmp6_patchtester_pulls_labels' doesn't exist 

### ISSUE THREAD

**Issue by N6REJ** [joomla-extensions/patchtester#347]
#### Steps to reproduce the issue
Install 4.2.1 on 4.2-dev J!
open patch tester

#### Expected result
no error shown

#### Actual result
![image](https://user-images.githubusercontent.com/1850089/189035330-049da188-899b-43cf-a887-993c9c2e84c3.png)

#### System information (as much as possible)

win 10 x64 pro

**Comment by richard67** [comment]
This happens when patchtester was installed before and you remove configuration.php and clean your database to make a new installation e.g. on a testing environment, and then install patchtester. The files and folders from the previous installation are still there, and then this happens. Just uninstall patchtester and install it again and it will be working.

This in an old and well known thing and I am pretty sure you ran into it in past and just have forgotten about it.

**Comment by N6REJ** [comment]
yep, that fixed it.  Your probably corrected.
