### ISSUE TITLE
No check of the GitHub account

### ISSUE THREAD

**Issue by garstud** [joomla-extensions/patchtester#86]
#### Steps to reproduce the issue
open the Options light box of Patch tester
set a wrong account in the options lightbox.
click on Save&close 
click on the Fetch data bouton

#### Expected result
a warning message must explain that the account is not correct.

#### Actual result
the lightbox of "Fecth Data" open and display the followwing message :
"Preparing to fetch GitHub data
Making sure all is well to fetch data. Sit tight."

#### System information (as much as possible)
Patch tester : v2.0.0.beta2	October 2011

**Comment by mbabker** [comment]
There were some places where the GitHub connection wasn't checking for errors, that error handling was added in now and everything correctly raises an error when bad credentials are supplied.

**Comment by garstud** [comment]
Great, thank you.

**Comment by gwsdesk** [comment]
I am experiencing this on Joomla 3.7-Alpha2 with PHP7. 

"Preparing to fetch GitHub data

Making sure all is well to fetch data. Sit tight."

My credentials are correct otherwise I could not login with Github here on Issues. 

I first fetched data with no credentials --> very quick fetching so no issues. I enter the credentials and fetch again and hangs with said message<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/patchtester/86">issues.joomla.org/tracker/patchtester/86</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@gwsdesk had same issue days ago. Reinstalled patchtester and token and it works.
